### ISSUE TITLE
Fix notation for number of bootstrap draws

### ISSUE THREAD

**Issue by jmshapir** [JMSLab/BootstrapReport#10]
In our [docs](https://github.com/JMSLab/BootstrapReport/blob/20d47d95e17dfeac27b17a51b82006aa4b92a4ef/BootstrapReport.lyx) we index bootstrap replicates with $s$ and we denote the number of replicates by $S$.

In the [draft](https://scholar.harvard.edu/sites/scholar.harvard.edu/files/shapiro/files/varest.pdf) we use $j$ and $J$, respectively.

Can you please update the docs to match the draft and open a pull assigned to @jmshapir?

Thanks!

**Comment by MosesStewart** [comment]
Summary: In this issue we . . .

- Updated the notation in `BootstrapReport.lyx` to index bootstrap replicates with `j` and indicate the number of replicates with `J` instead of `s` and `S`

Changes made into `main` 8cc064d
