### ISSUE TITLE
Format of p-p plots

### ISSUE THREAD

**Issue by jmshapir** [JMSLab/BootstrapReport#13]
Issue to start once #12 is fully merged.

The below is from [Figure 1 of the posted draft](https://scholar.harvard.edu/sites/scholar.harvard.edu/files/shapiro/files/varest.pdf#page=33).

Two things:
- [x] Let's change "CDF of comparison distribution" to "CDF of bootstrap distribution"
- [x] Let's have the axes run only over $[0,1]$ (to avoid the potential confusion of implying that a CDF can take on values outside this range)
- [x] Let's see if we can make the shaded region a bit darker by default

![image](https://github.com/JMSLab/BootstrapReport/assets/7840353/db65e9f7-4d2d-4a5f-bc99-6010a5d9d9a6)

**Comment by MosesStewart** [comment]
@jmshapir here are examples of the new plot:

![gamma_plot](https://github.com/JMSLab/BootstrapReport/assets/111905359/3b3864e6-691c-471b-82f6-c082aadc4d08)
![normal_plot](https://github.com/JMSLab/BootstrapReport/assets/111905359/1aea23e8-1f6c-4823-9a05-ad14b07d89a6)

**Comment by jmshapir** [comment]
@MosesStewart that looks good to me except I don't think we want the legend spilling over the axis if we can avoid it.

After you fix that can you open a pull for @jmshapir to review? Thanks!

**Comment by jmshapir** [comment]
[Removed below from roadmap](https://github.com/JMSLab/BootstrapReport/wiki/Roadmap/_compare/0b4b48ff23c7d857c60e648309c9fb7ea1b57671...110736a3b8994366e104508d7e4cd2bcc8a3ca5a)

> * PP plots
>   * Change default y-axis title "CDF of comparison distribution" to "CDF of bootstrap distribution"
>   * Consider truncating axes at $[0,1]$
