### ISSUE TITLE
Deploy to shiny

### ISSUE THREAD

**Issue by jmshapir** [JMSLab/BootstrapReport#18]
We'd like to set up a [shiny app](https://shiny.posit.co/py/) hosted in [shinyapps.io](https://shiny.posit.co/py/docs/deploy-cloud.html) that has the following properties.
  * User inputs
     * Point estimate
     * Standard error
     * CSV file containing bootstrap replicates
  * App returns
     * p-p plot
     * sk-minimizing mean, sd
     * sk of bootstrap distribution to both the default normal report and the sk-minimizing report
  * Deployment
     * you should be able to set up a free account at [shinyapps.io](https://shiny.posit.co/py/docs/deploy-cloud.html) 
     * once we have the deployment working in your free instance we can port it to a paid instance that I maintain
     * ideally the app will call `BootstrapReport` as a requirement; i.e. we won't need to "ship" the `BootstrapReport` library along with the app
     * the app can direct users to this repository for more information about the functionality of the library, documentation, etc

**Comment by MosesStewart** [comment]
Summary: In this issue we . . .

- Updated the plotting functions in `main.py` and `helpers.py` to use `fig` and `ax` objects from `matplotlib.pyplot.subplots()` instead of creating plots from the `matplotlib.pyplot` class
    - Allows us to return the `fig` object, which is a requirement for displaying figures on `shiny`
    
 Changes made into `main`: a971040
