### ISSUE TITLE
Confidence interval for SK distance

### ISSUE THREAD

**Issue by jmshapir** [JMSLab/BootstrapReport#19]
Add `get_sk_ci` to [`helpers`](https://github.com/JMSLab/BootstrapReport/blob/1f327a7b1dcefae1a9901fbd8bb38b88faa9a057/src/BootstrapReport/helpers.py):
* Inputs
  * Number of replicates
  * Maximum positive distance, maximum negative distance
  * Alpha (defaults to 0.05)
* Outputs
  * Lower bound of CI, upper bound of CI
* Methods
  * See section [confidence interval for SK distance](https://github.com/JMSLab/BootstrapReport/blob/f5b629b88298a734ca7cd5be6837c961ce9f80f2/BootstrapReport.lyx#L298) in docs

Add to [initialization block in `main`](https://github.com/JMSLab/BootstrapReport/blob/1f327a7b1dcefae1a9901fbd8bb38b88faa9a057/src/BootstrapReport/main.py#L15-L28) code that looks roughly like this:

```
 [self.sk_pos, self.sk_neg] = helpers.get_sk_dist(self.replicates, norm(loc = estimate, scale = se), sep = True)
 [self.sk_ci_lb, self.sk_ci_ub] = helpers.get_sk_ci(leng(self.replicates), self.sk_pos, self.sk_neg)
```

**Comment by jmshapir** [comment]
@isandrews in f5b629b I sketched the methods I think we should use here. (Snip below for convenience.)

Can you let me know if this looks right?

(If you like, feel free to also check the design in https://github.com/JMSLab/BootstrapReport/issues/19#issue-2002786349.)

![image](https://github.com/JMSLab/BootstrapReport/assets/7840353/415a431e-ad59-45a1-8f2a-8761f5dcdac4)

**Comment by isandrews** [comment]
Looks good to me - thanks @jmshapir!

**Comment by rcalvo12** [comment]
@jmshapir, I added the function for producing the SK CI's in https://github.com/JMSLab/BootstrapReport/commit/b547b56c23024fd549af4af9d7fd72e91f1cedaf.

**Comment by jmshapir** [comment]
@rcalvo12 great thanks! Let's add a unit test and open a pull with @isandrews @jmshapir @MosesStewart as reviewers.

**Comment by rcalvo12** [comment]
Thread continues in #20.

**Comment by rcalvo12** [comment]
**Summary:**

In this issue we added a function for calculating confidence intervals for the SK distance as well as unit testing.

Merged in https://github.com/JMSLab/BootstrapReport/commit/2cfe33c2e0563a69893f9fc13cd2ca90c7c126d6.
Final state of issue branch [here](https://github.com/JMSLab/BootstrapReport/tree/c35d8313352ebc35dae5002e1f645abc5a3807c0).
